name: Release
on: [ workflow_dispatch ] # Manual trigger

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-22.04
        container:
            image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
            options: --user root
        steps:
            -   uses: actions/checkout@v4
            -   name: Set execute permissions for gradlew
                run: chmod +x gradlew
            -   name: Build and Publish Mods
                run: ./gradlew build publishMods
                env:
                    CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
                    MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    BUILD_RELEASE: true
                    BUILD_ID: ${{ github.run_number }}
